$cfg['blowfish_secret'] = 'dV2mIRtPP,XK=1wbPJxQt83Ys54POLAP';
$i = 0;
i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['Servers'][$i]['controluser'] = 'root';
$cfg['Servers'][$i]['controlpass'] = '';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
